In [1]:
import pandas as pd

In [2]:
tournaments = {}
# tournaments["London 2018"] = [
#     "compLexity Gaming", "Team Liquid", "Astralis", "Natus Vincere", "BIG",
#     "FaZe Clan", "HellRaisers", "MIBR", "Ninjas in Pyjamas", "Fnatic",
#     "G2 Esports", "Vega Squadron", "Cloud9", "Tyloo", "Winstrike Team",
#     "mousesports"
# ]
tournaments["Boston 2018"] = [
    "Cloud9", "G2 Esports", "FaZe Clan", "Vega Squadron", "Space Soldiers",
    "mousesports", "Natus Vincere", "Quantum Bellator Fire", "Team Liquid",
    "Renegades", "Avangar", "Sprout Esports", "Team EnVyUs", "Misfits Gaming",
    "Flash Gaming", "Flipsid3 Tactics", "Gambit Esports", "Astralis", "Virtus.Pro", 
    "Fnatic", "SK Gaming", "BIG", "North"
]
tournaments["Krakow 2017"] = [
    "Gambit", "BIG", "SK Gaming", "North", "Astralis", "Virtus.Pro",
    "Immortals", "Fnatic", "Cloud9", "Flipsid3 Tactics", "G2 Esports",
    "Natus Vincere", "mousesports", "PENTA Sports", "FaZe Clan",
    "Vega Squadron"
]
tournaments["Atlanta 2017"] = [
    "Gambit Gaming", "Team Liquid", "SK Gaming", "North", "Astralis", "Virtus.Pro",
    "GODSENT", "Fnatic", "OpTic Gaming", "Flipsid3 Tactics", "G2 Esports",
    "Natus Vincere", "mousesports", "Team EnVyUs", "FaZe Clan", "HellRaisers"
]
tournaments["MLG Columbus 2016"] = [
    "Ninjas in Pyjamas", "G2 Esports", "Splyce", "Cloud9", "Team EnVyUs", "Virtus.Pro",
    "Astralis", "Fnatic", "Counter Logic Gaming", "Team Liquid", "FaZe Clan",
    "Natus Vincere", "Gambit Gaming", "Flipsid3 Tactics", "mousesports", "Luminosity Gaming"
]
tournaments["Cologne 2016"] = [
    "Ninjas in Pyjamas", "G2 Esports", "OpTic Gaming", "Team Dignitas", "Team EnVyUs", "Virtus.Pro",
    "Astralis", "Fnatic", "Counter Logic Gaming", "Team Liquid", "FaZe Clan",
    "Natus Vincere", "Gambit Gaming", "Flipsid3 Tactics", "mousesports", "SK Gaming"
]
tournaments["Cologne 2015"] = [
    "Ninjas in Pyjamas", "Titan", "Luminosity Gaming", "Cloud9 G2A", "Team EnVyUs", "Virtus.Pro",
    "Team SoloMid", "Fnatic", "Counter Logic Gaming", "Team Immunity", "Team Kinguin",
    "Natus Vincere", "Team eBettle", "Flipsid3 Tactics", "mousesports", "Renegades"
]
tournaments["Cluj-Napoca 2015"] = [
    "Ninjas in Pyjamas", "G2 Esports", "Cloud9", "Team Dignitas", "Team EnVyUs", "Virtus.Pro",
    "Team SoloMid", "Fnatic", "Counter Logic Gaming", "Team Liquid", "Titan",
    "Natus Vincere", "Vexed Gaming", "Flipsid3 Tactics", "mousesports", "Luminosity Gaming"
]
tournaments["Katowice 2015"] = [
    "Ninjas in Pyjamas", "PENTA Sports", "Cloud9 G2A", "HellRaisers", "Team EnVyUs", "Virtus.pro",
    "Team SoloMid", "Fnatic", "Counter Logic Gaming", "LGB eSports", "Titan",
    "Natus Vincere", "3DMAX", "Flipsid3 Tactics", "Vox Eminor", "Keyd Stars"
]
tournaments["Cologne 2014"] = [
    "Ninjas in Pyjamas", "Team Dignitas", "Cloud9", "HellRaisers", "Team LDLC.com", "Virtus.Pro",
    "London Conspiracy", "Fnatic", "dAT Team", "Epsilon eSports", "Titan",
    "Natus Vincere", "Copenhagen Wolves", "Team iBUYPOWER", "Vox Eminor", "MTS GameGod Wolf"
]
tournaments["DreamHack 2014"] = [
    "Ninjas in Pyjamas", "Team Dignitas", "Cloud9", "HellRaisers", "Team LDLC.com", "Virtus.Pro",
    "Planetkey Dynamics", "Fnatic", "PENTA Sports", "ESC Gaming", "myXMG",
    "Natus Vincere", "Copenhagen Wolves", "Team iBUYPOWER", "Bravado Gaming", "Flipsid3 Tactics"
]

teams = {"Astralis" : "Denmark", "Virtus.Pro" : "Poland", 'Fnatic' : "Sweden", "SK Gaming" : "Brazil",
        "Natus Vincere" : "CIS", "Gambit" : "CIS", "North" : "Denmark", "FaZe Clan" : "International",
        "Team EnVyUs" : "France", "GODSENT" : "Sweden", "Team Liquid" : "USA", "OpTic Gaming" : "USA", 
        "G2 Esports" : "France", "mousesports" : "International", "Flipsid3 Tactics" : "CIS", 
        "HellRaisers" : "CIS", "compLexity Gaming" : "USA", "BIG" : "Germany", "MIBR" : "Brazil", 
        "Ninjas in Pyjamas" : "Sweden", "Vega Squadron" : "CIS", "Cloud9" : "USA", "Tyloo" : "China",
        "Winstrike Team" : "CIS", "Space Soldiers" : "Turkey", "Quantum Bellator Fire" : "CIS", 
        "Renegades" : "Australia", "Avangar" : "CIS", "Sprout Esports" : "Germany", 
        "Flash Gaming" : "China", "Immortals" : "Brazil", "PENTA Sports" : "International", 
        "Counter Logic Gaming" : "USA", "Luminosity Gaming" : "Brazil", "Team Dignitas" : "Denmark",
        "Titan" : "France", "Team SoloMid" : "Denmark", "Team Immunity" : "Australia", 
        "Team Kinguin" : "International", "Team eBettle" : "Poland", "Vexed Gaming" : "Poland",
        "3DMAX" : "Finland", "Vox Eminor" : "Australia", "Keyd Stars" : "Brazil", 
        "London Conspiracy" : "Norway", "dAT Team" : "CIS", "Epsilon eSports" : "France", 
        "Copenhagen Wolves" : "Denmark", "Team iBUYPOWER" : "USA", "MTS GameGod Wolf" : "India", 
        "Planetkey Dynamics" : "Germany", "ESC Gaming" : "Poland", "myXMG" : "Denmark", 
        "Bravado Gaming" : "South Africa", "Misfits Gaming" : "USA", "Splyce" : "USA", 
        "LGB eSports" : "Norway", "Team LDLC.com" : "France"}

In [3]:
# raw_features = pd.read_csv("raw_features.csv")
# #raw_features
# #raw_features.replace({"country": di})
# raw_features['country'] = raw_features['team'].map(teams)
# raw_features.to_csv("features.csv")
# raw_features
# temp = []#pd.DataFrame(columns=['value'])
# for index, row in raw_features.iterrows():
#     tournament = row['tournament']
#     team = row['team']
#     tempdata = pd.read_csv("market_data/"+tournament+"/"+team+".csv")
#     val = tempdata.iloc[-1, 1]
#     temp.append(val)

# se = pd.Series(temp)
# raw_features['value'] = se.values
# raw_features


# raw_features.to_csv("features.csv", index = False)
# raw_features.iloc[-1, raw_features.columns.get_loc('team')]
# temp = pd.read_csv("market_data/"+'Atlanta 2017'+"/"+'Astralis'+".csv")
# temp.iloc[-1, 1]

In [4]:
raw_features = pd.read_csv("features.csv")
raw_features = raw_features.applymap(lambda s:s.lower() if type(s) == str else s)
raw_features

            tournament                   team  placing        country   value
0         atlanta 2017               astralis        1        denmark   1.690
1         atlanta 2017             virtus.pro        2         poland   0.728
2         atlanta 2017                 fnatic        4         sweden   1.152
3         atlanta 2017              sk gaming        4         brazil   0.610
4         atlanta 2017          natus vincere        8            cis   1.497
5         atlanta 2017                 gambit        8            cis   0.360
6         atlanta 2017                  north        8        denmark   0.413
7         atlanta 2017              faze clan        8  international   2.427
8         atlanta 2017            team envyus       11         france   0.500
9         atlanta 2017                godsent       11         sweden   1.100
10        atlanta 2017            team liquid       11            usa   1.505
11        atlanta 2017           optic gaming       14            usa   0.800
12        atlanta 2017             g2 esports       14         france   1.504
13        atlanta 2017            mousesports       14  international   1.010
14        atlanta 2017       flipsid3 tactics       16            cis   0.851
15        atlanta 2017            hellraisers       16            cis   0.844
16         boston 2018                 cloud9        1            usa   0.520
17         boston 2018              faze clan        2  international   0.572
18         boston 2018          natus vincere        4            cis   0.610
19         boston 2018              sk gaming        4         brazil   0.284
20         boston 2018            mousesports        8  international   0.320
21         boston 2018  quantum bellator fire        8            cis   0.185
22         boston 2018             g2 esports        8         france   0.319
23         boston 2018                 fnatic        8         sweden   0.470
24         boston 2018         space soldiers        9         turkey   0.564
25         boston 2018                 gambit        9            cis   0.249
26         boston 2018          vega squadron        9            cis   0.197
27         boston 2018            team liquid       12            usa   0.757
28         boston 2018               astralis       12        denmark   1.002
29         boston 2018                    big       12        germany   0.308
..                 ...                    ...      ...            ...     ...
130  mlg columbus 2016               astralis        4        denmark   0.694
131  mlg columbus 2016            team liquid        4            usa   0.562
132  mlg columbus 2016      ninjas in pyjamas        8         sweden   0.459
133  mlg columbus 2016                 fnatic        8         sweden   0.405
134  mlg columbus 2016   counter logic gaming        8            usa   0.412
135  mlg columbus 2016             virtus.pro        8         poland   0.510
136  mlg columbus 2016            mousesports       12  international   0.388
137  mlg columbus 2016              faze clan       12  international   0.547
138  mlg columbus 2016                 gambit       12            cis   0.260
139  mlg columbus 2016             g2 esports       12         france   0.718
140  mlg columbus 2016       flipsid3 tactics       16            cis   0.453
141  mlg columbus 2016                 splyce       16            usa   0.389
142  mlg columbus 2016            team envyus       16         france   0.434
143  mlg columbus 2016                 cloud9       16            usa   0.907
144     dreamhack 2014          team ldlc.com        1         france   2.093
145     dreamhack 2014      ninjas in pyjamas        2         sweden   1.778
146     dreamhack 2014             virtus.pro        4         poland   1.790
147     dreamhack 2014          natus vincere        4            cis   2.812
148     dreamhack 2014            hellraisers        8            cis   2.518
149     dreamhack 2014           penta sports        8  international   1.875
150     dreamhack 2014                 fnatic        8         sweden   1.410
151     dreamhack 2014          team dignitas        8        denmark   3.002
152     dreamhack 2014                 cloud9       12            usa   6.450
153     dreamhack 2014         team ibuypower       12            usa  19.980
154     dreamhack 2014             esc gaming       12         poland   3.114
155     dreamhack 2014       flipsid3 tactics       12            cis   1.741
156     dreamhack 2014         bravado gaming       16   south africa   3.285
157     dreamhack 2014      copenhagen wolves       16        denmark   3.630
158     dreamhack 2014     planetkey dynamics       16        germany   4.330
159     dreamhack 2014                  myxmg       16        denmark   3.219

[160 rows x 5 columns]

In [5]:
from sklearn import preprocessing

def prep(df, col):
    le = preprocessing.LabelEncoder()
    if col == 'tournament':
        lst = [x.lower() for x in list(tournaments.keys())]
        le.fit(lst)
    elif col == 'team':
        lst = [x.lower() for x in list(teams.keys())]
        le.fit(lst)
    elif col == 'country':
        lst = [x.lower() for x in list(teams.values())]
        le.fit(lst)
    
    return le

le_tour = prep(raw_features, 'tournament')
le_team = prep(raw_features, 'team')
le_coun = prep(raw_features, 'country')

#le_tour.transform(x['tournament'])

In [6]:
tour_list = le_tour.transform(raw_features['tournament'])
se = pd.Series(tour_list)
raw_features['tournament'] = se.values

team_list = le_team.transform(raw_features['team'])
se = pd.Series(team_list)
raw_features['team'] = se.values

coun_list = le_coun.transform(raw_features['country'])
se = pd.Series(coun_list)
raw_features['country'] = se.values

raw_features

     tournament  team  placing  country   value
0             0     1        1        4   1.690
1             0    55        2       11   0.728
2             0    15        4       13   1.152
3             0    38        4        1   0.610
4             0    30        8        3   1.497
5             0    17        8        3   0.360
6             0    32        8        4   0.413
7             0    12        8        9   2.427
8             0    44       11        6   0.500
9             0    18       11       13   1.100
10            0    49       11       15   1.505
11            0    33       14       15   0.800
12            0    16       14        6   1.504
13            0    27       14        9   1.010
14            0    14       16        3   0.851
15            0    19       16        3   0.844
16            1     5        1       15   0.520
17            1    12        2        9   0.572
18            1    30        4        3   0.610
19            1    38        4        1   0.284
20            1    27        8        9   0.320
21            1    36        8        3   0.185
22            1    16        8        6   0.319
23            1    15        8       13   0.470
24            1    39        9       14   0.564
25            1    17        9        3   0.249
26            1    53        9        3   0.197
27            1    49       12       15   0.757
28            1     1       12        4   1.002
29            1     3       12        7   0.308
..          ...   ...      ...      ...     ...
130           9     1        4        4   0.694
131           9    49        4       15   0.562
132           9    31        8       13   0.459
133           9    15        8       13   0.405
134           9     8        8       15   0.412
135           9    55        8       11   0.510
136           9    27       12        9   0.388
137           9    12       12        9   0.547
138           9    17       12        3   0.260
139           9    16       12        6   0.718
140           9    14       16        3   0.453
141           9    40       16       15   0.389
142           9    44       16        6   0.434
143           9     5       16       15   0.907
144           6    48        1        6   2.093
145           6    31        2       13   1.778
146           6    55        4       11   1.790
147           6    30        4        3   2.812
148           6    19        8        3   2.518
149           6    34        8        9   1.875
150           6    15        8       13   1.410
151           6    42        8        4   3.002
152           6     5       12       15   6.450
153           6    45       12       15  19.980
154           6    11       12       11   3.114
155           6    14       12        3   1.741
156           6     4       16       12   3.285
157           6     7       16        4   3.630
158           6    35       16        7   4.330
159           6    29       16        4   3.219

[160 rows x 5 columns]

In [8]:
#raw_features.to_csv("encoded_features.csv", index = False)

In [9]:
from sklearn.model_selection import train_test_split
def x_y_split(data):
    x = ['tournament','team','placing','country']
    y = ['value']
    return data[x], data[y]
x,y = x_y_split(raw_features)

In [10]:
import xgboost as xgb
xgreg = xgb.XGBRegressor(seed = 10, random_state = 10)
xgreg.fit(x,y)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='reg:linear', random_state=10,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=10, silent=True,
       subsample=1)

In [24]:
le_tour.transform(['boston 2018'])

array([1])

In [28]:
def tour_split(data, tour):
    """
    tour : number from 0-9
    returns: everything else, specific tour
    """
    a = data.loc[data['tournament'] != tour]
    b = data.loc[data['tournament'] == tour]
    return a,b

In [30]:
train, test = tour_split(raw_features, 1)
train_x, train_y = x_y_split(train)
test_x, test_y = x_y_split(test)

In [31]:
xgreg = xgb.XGBRegressor(seed = 10, random_state = 10)
xgreg.fit(train_x,train_y)
xgreg.predict(test_x)

array([ 1.51616168,  0.8851974 ,  0.90745723,  0.64164865,  0.61947912,
        0.91835111,  0.60854983,  0.47203803,  0.91944265,  0.59699023,
        0.69564545,  1.55302441,  1.66586268,  0.84321439,  0.62816006,
        0.87720859], dtype=float32)

In [37]:
test_x

    tournament  team  placing  country
16           1     5        1       15
17           1    12        2        9
18           1    30        4        3
19           1    38        4        1
20           1    27        8        9
21           1    36        8        3
22           1    16        8        6
23           1    15        8       13
24           1    39        9       14
25           1    17        9        3
26           1    53        9        3
27           1    49       12       15
28           1     1       12        4
29           1     3       12        7
30           1    32       15        4
31           1    55       15       11

In [38]:
# Top 4:
#28, 27, 16, 24
#
#1.002, 0.757, 0.52, 0.564
4*(1.002+0.757+ 0.52+ 0.564)

11.372

In [36]:
pd.read_csv("features.csv").iloc[16:32]

     tournament                   team  placing        country  value
16  Boston 2018                 Cloud9        1            USA  0.520
17  Boston 2018              FaZe Clan        2  International  0.572
18  Boston 2018          Natus Vincere        4            CIS  0.610
19  Boston 2018              SK Gaming        4         Brazil  0.284
20  Boston 2018            mousesports        8  International  0.320
21  Boston 2018  Quantum Bellator Fire        8            CIS  0.185
22  Boston 2018             G2 Esports        8         France  0.319
23  Boston 2018                 Fnatic        8         Sweden  0.470
24  Boston 2018         Space Soldiers        9         Turkey  0.564
25  Boston 2018                 Gambit        9            CIS  0.249
26  Boston 2018          Vega Squadron        9            CIS  0.197
27  Boston 2018            Team Liquid       12            USA  0.757
28  Boston 2018               Astralis       12        Denmark  1.002
29  Boston 2018                    BIG       12        Germany  0.308
30  Boston 2018                  North       15        Denmark  0.262
31  Boston 2018             Virtus.pro       15         Poland  0.424